name: tubes_pbp_9
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
<<<<<<< Updated upstream
=======
  video_player: ^2.6.1
  http: ^1.2.2
  flutter_riverpod: ^2.6.1
<<<<<<< Updated upstream
  mobile_scanner: ^3.2.0
  path_provider: ^2.0.15
  qr_flutter: ^4.1.0
  camera: ^0.11.0
>>>>>>> Stashed changes
=======
  image_picker: ^0.8.7+5
  fluttertoast: ^8.0.9
  photo_manager: ^2.6.0
>>>>>>> Stashed changes

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
<<<<<<< Updated upstream
          weight: 700
=======
          weight: 700
  assets:
    - assets/combo1.jpg
    - assets/combo2.jpg
    - assets/coke.jpg
    - assets/fries.jpg
    - assets/popcorn_l.png
    - assets/popcorn_m.png
    - assets/popcorn_r.png
    - assets/sprite.jpg
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
    - assets/images/avengers.jpeg
    - assets/images/spiderman.jpg
    - assets/images/ironman.jpeg
    - assets/images/ryan.jpg
>>>>>>> Stashed changes
