name: tubes_pbp_9
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  carousel_slider: ^5.0.0
  http: ^1.2.2
  flutter_riverpod: ^2.6.1
  image_picker: ^0.8.7+5
  fluttertoast: ^8.0.9
  photo_manager: ^2.6.0
  flutter_secure_storage: ^5.0.2
  youtube_player_flutter: ^8.0.0
  flutter_tts: ^3.6.4
  intl: ^0.18.0
  barcode_widget: ^2.0.1
  pdf: ^3.10.2
  printing: ^5.9.0
  path_provider: ^2.0.11

dev_dependencies:
  camera: ^0.10.5+2 # access to hardware
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  qr_flutter: ^4.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
  assets:
    - assets/combo1.jpg
    - assets/combo2.jpg
    - assets/coke.jpg
    - assets/fries.jpg
    - assets/popcorn_l.png
    - assets/popcorn_m.png
    - assets/popcorn_r.png
    - assets/sprite.jpg
    - assets/images/avengers.jpeg
    - assets/images/spiderman.jpg
    - assets/images/ironman.jpeg
    - assets/images/ryan.jpg
    - assets/posterFilm/cars2Poster.jpg
    - assets/posterFilm/dunePoster.jpg
    - assets/posterFilm/dunkirkPoster.jpg
    - assets/posterFilm/gotg2Poster.jpg
    - assets/posterFilm/interstellarPoster.jpg
    - assets/posterFilm/parasitePoster.jpg
    - assets/backgroundLoading.jpg
    - assets/qris.png
